privacybydesign/irmamobile

assets/locales/en.json
Fixed some language strings. This is my first GitHub contribution... I hope this is the right way to do this!
=> Remove duplicate sentence and change "data" to singular

lib/src/screens/session/disclosure/widgets/disclosure_permission_choices_screen.dart
Changed the change choice link in the disclosure permission flow to a button.
=> feat: changed change choice link to button

integration_test/irma_binding.dart, lib/main.dart, lib/src/data/irma_client_bridge.dart
Such that we can trace errors in iOS integration test runs.
=> Test: enable debug logging in release mode integration test runs

CHANGELOG.md, go.mod, go.sum, pubspec.yaml
Relates to https://github.com/privacybydesign/irmago/pull/285
=> Fix: resolve 'Cannot initialize client: no scheme file found' errors

.github/actions/setup-build-environment/action.yml
fixes: https://github.com/privacybydesign/irmamobile/issues/117
=> fix: bumped go version in action

lib/src/screens/session/session_screen.dart
=> Fix: invalid null assertion made in dispose on SessionScreen

lib/src/screens/activity/history_repository.dart
=> Fix: prevent unmodifiable list errors to occur in HistoryRepository

lib/src/screens/session/widgets/arrow_back_screen.dart
Note: this has to be tested on a real device.
=> fix: arrow back screen points to the wrong corner in landscape

android/app/build.gradle
https://support.google.com/googleplay/android-developer/answer/11926878
=> Chore: update Android target SDK version to 33

assets/locales/en.json, assets/locales/nl.json, integration_test/enroll_test.dart, integration_test/helpers/helpers.dart, integration_test/settings_test.dart, lib/app.dart, lib/main.dart, lib/routing.dart, lib/src/data/irma_preferences.dart, lib/src/screens/change_language/change_language_screen.dart, lib/src/screens/change_language/widgets/change_language_radio.dart, lib/src/screens/change_language/widgets/language_radio.dart, lib/src/screens/change_language/widgets/system_language_toggle.dart, lib/src/screens/more/widgets/tiles_radio.dart, lib/src/screens/settings/settings_screen.dart, lib/src/util/language.dart, lib/src/widgets/preferred_language_builder.dart
=> feat: change language in app

CHANGELOG.md, go.mod, go.sum, integration_test/irma_binding.dart
Includes fix that blocked #185
=> Chore: bump irmago version to 0.12.4

CHANGELOG.md, irmagobridge/bridge.go, irmagobridge/error_reporter.go
Changes from #185 that were not included in #186.
=> Chore: report warnings from irmago to Sentry

integration_test/disclosure_session/special_scenarios/revocation.dart, integration_test/issue_wizard_test.dart, integration_test/more_tab_test.dart
On some devices (like Samsung Galaxy S9) the tests fail in landscape mode
=> test: scroll issues in integration tests

CHANGELOG.md, android/app/src/main/java/foundation/privacybydesign/irmamobile/irma_mobile_bridge/IrmaMobileBridge.java
=> Chore: include the cause of Android key store exceptions in Sentry reports

integration_test/enroll_test.dart
Weekly status checks were failing. This PR fixes this.
=> Test: fix failing provide-email integration test

android/app/build.gradle, ci_scripts/install_android_sdk.sh
=> Chore: increase Android API target to 34

assets/locales/en.json, assets/locales/nl.json, integration_test/enroll_test.dart, lib/app.dart, lib/main.dart, lib/src/screens/data/widgets/credential_category_list.dart, lib/src/screens/home/home_screen.dart, lib/src/screens/home/widgets/irma_nav_button.dart, lib/src/screens/issue_wizard/issue_wizard.dart, lib/src/screens/more/widgets/tiles.dart, lib/src/screens/notifications/widgets/notification_bell.dart, lib/src/screens/settings/settings_screen.dart, lib/src/widgets/collapsible.dart, lib/src/widgets/credential_card/irma_credential_card_header.dart, lib/src/widgets/credential_card/irma_credential_type_card.dart, lib/src/widgets/yivi_themed_button.dart
This PR aims to improve navigation for visually impaired people by improving screen reader support.
- Explicitly mention tab buttons and their index
- Hide some unimportant images and icons from screen reader
- Improve descriptions for Collapsable widget
- Fix pronunciation of "Notificatiebel"
- Fix description of switches
Some other minor fixes:
- Use correct link for Yivi meetups
- Fix linter warning about super class constructor params
=> improve semantics for voice over

CHANGELOG.md
=> add compare line to changelog for v7.7.0

integration_test/activity_test.dart, integration_test/disclosure_session/filled_app_scenarios/filled_choice_mixed.dart, integration_test/disclosure_session/filled_app_scenarios/filled_discon.dart, integration_test/disclosure_session/filled_app_scenarios/filled_no_choice_multiple_creds.dart, integration_test/disclosure_session/filled_app_scenarios/filled_optional_disjunction.dart, integration_test/disclosure_session/filled_app_scenarios/filled_specific_attribute_values_match.dart, integration_test/disclosure_session/filled_app_scenarios/filled_specific_attribute_values_no_match.dart, integration_test/disclosure_session/special_scenarios/calling_session.dart, integration_test/disclosure_session/special_scenarios/revocation.dart, integration_test/disclosure_session/special_scenarios/signing.dart, integration_test/helpers/helpers.dart, lib/src/data/irma_repository.dart
From `https://demo.privacybydesign.foundation` to `https://is.demo.staging.yivi.app`
=> Use new demo irma server for integration tests

CHANGELOG.md, android/app/src/main/AndroidManifest.xml, integration_test/disclose_sdjwt_over_openid4vp_test.dart, ios/Runner/Info.plist, lib/src/models/session.dart
=> Add `openid4vp://` scheme support
